# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-10 17:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20171010_1659'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='isbn13',
            new_name='isbn_13',
        ),
        migrations.AlterField(
            model_name='product',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Customer'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(max_length=300),
        ),
    ]
