# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-10 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20171010_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cover',
            field=models.ImageField(default='api/static/images/no_image.gif', upload_to='api/static/images/'),
        ),
    ]
