# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-10 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20171010_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cover',
            field=models.ImageField(upload_to='images'),
        ),
    ]
