# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-10 21:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20171010_1656'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Book',
        ),
        migrations.AlterModelTable(
            name='book',
            table='book',
        ),
    ]
