# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-11 15:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20171010_1740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='pid',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='uid',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
