# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-12 13:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20171011_1109'),
        ('orders', '0002_auto_20171011_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='book',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, related_name='orderitems', to='api.Book'),
            preserve_default=False,
        ),
    ]
