# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-12 13:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='book',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, to='api.Book'),
        ),
    ]
