# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-12 16:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20171012_0913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='book',
        ),
    ]
