# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-12 18:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_order_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover', models.ImageField(upload_to='static/images')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('isbn_13', models.CharField(max_length=13)),
                ('author_first_name', models.CharField(max_length=20)),
                ('author_last_name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'book',
            },
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='orders.Book'),
        ),
    ]
